### ISSUE TITLE
ui-test flake: testBackgroundReturnPreservesSessionKeyboardAndBackResponsiveness times out a 10s AX wait while the app reports connected

### ISSUE THREAD

**Issue by cad0p** [cad0p/vvterm#232]
## Symptom

`ui-tests-shard-3` failed in PR #226's CI (run `35949194871`, job `107476167993`,
head `c1e50518`):

```
VVTermUITests/ServerNavigationUITests.swift:505: error:
-[VVTermUITests.ServerNavigationUITests testBackgroundReturnPreservesSessionKeyboardAndBackResponsiveness] :
XCTAssertEqual failed: ("XCTWaiterResult(rawValue: 2)") is not equal to ("XCTWaiterResult(rawValue: 1)")
- Timed out waiting for state=connected. setup=ready state=connected title=DEV199_READY_1
cwd=/tmp/DEV199_INPUT_X_1 failure=none disconnectReason=none connectionAttempt…
```

The test failed at 172.1 s; the shard executed 20 tests in 701.8 s (its LPT bin
sum is ~527 s → the runner was ~1.4× loaded).

## Diagnosis

- `ServerNavigationUITests.wait(for:containing:timeout:app:)` defaults to
  **`timeout: TimeInterval = 10`** — a 10 s `XCTNSPredicateExpectation` against
  the diagnostics label. On a loaded 4-shard runner the AX tree can lag past
  10 s, so the expectation times out even though the app state is already
  correct: the failure payload says `state=connected … failure=none`.
- The same 10 s-budget class as **#220**
  (`testProductionCodexFindKeyboardMenuRestoresPTYTyping`).
- **The shard retry cannot absorb it.** The harness surfaces the timeout as
  `XCTAssertEqual`, so Case 2's zero-assertion gate (`! grep -q "XCTAssert"`)
  rejects it, and Case 2a's `scene=…(rawValue: 0).*sentCount=0` signature does
  not match. The CI-hardening plan's Case 2 comment calls the wait-helper
  timeout an AX-wedge signature, but only "when it appears with zero XCTAssert
  failures" — this call site asserts the waiter result, so it never does.
- The shard's own budget guard then correctly declined a retry
  (`Not retrying: attempt cost 1023s, 1141s elapsed, 2100s job cap.`) — the
  attempt was too expensive to repeat, which is the intended behaviour.

## Options

1. **Raise the harness wait budget** for UI-sync waits (10 s → 20–30 s). The
   wait synchronises on the AX tree, not on a product SLA; 10 s is tight on a
   loaded runner and is the direct cause here. Same treatment as #220's budget.
2. **Make the retry predicate understand the class**: treat a wait-helper
   timeout whose payload shows `failure=none` (and, for the reconnect family,
   `state=connected`) as retryable, i.e. relax the zero-assertion gate for this
   specific signature.
3. Both — (1) removes the trip, (2) catches the residual cases.

Option (1) is the smaller, more honest fix; (2) needs care not to mask real
regressions (a genuinely broken connection also fails with `failure=none`, so
the payload must be read precisely).

## Acceptance

- The failure class no longer trips on a loaded runner (repeat CI runs with
  shard-3's bin).
- If the predicate is extended: a synthetic log of this signature retries,
  while a real product failure (e.g. `failure=timeout`, `disconnectReason=…`)
  still fails on attempt 1.

## Notes

- Found while landing #226 (a `unit-tests`-job-only change); the diff cannot
  affect UI shards, so the failure is unrelated and the job was re-run once
  with this issue recorded as the justification.
